### ISSUE TITLE
link break

### ISSUE THREAD

**Issue by fom78** [mdo/code-guide#258]
Bootstrap property order for Stylelint.
https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/main/css/index.js

**Comment by wenyuan** [comment]
> Bootstrap property order for Stylelint. https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/main/css/index.js

I happened to be in the same situation, after reviewing the commit history, I found [this commit](https://github.com/twbs/stylelint-config-twbs-bootstrap/commit/8628f1637e1dddac824566e726d0281ddd100d2c): Switch to stylelint-config-recess-order.

So now, you can get the properties-order in [this page](https://github.com/twbs/stylelint-config-twbs-bootstrap/commit/8628f1637e1dddac824566e726d0281ddd100d2c).

But I recommend jumping to the dependency library [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order) and then find the properties-order in  `index.js`, because more new properties are supported such as `grid`.

Hope this helps.

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!
