### ISSUE TITLE
Attribute order - id first

### ISSUE THREAD

**Issue by mahnunchik** [mdo/code-guide#26]
Maybe there is sense to use the id attribute first?
In this order:
- id
- class
- data-*
- src, for, type, href

Arguments:
1. Using id attribute is less than using classes but often more important for the application logic
2. String of classes can be very long and we may miss the id attribute

Example from http://getbootstrap.com/
`<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">`
I prefer:
`<header id="top" class="navbar navbar-static-top bs-docs-nav" role="banner">`

**Comment by mdo** [comment]
More than anything else, my reasoning has been doing classes first because it's from general to specific.

**Comment by mahnunchik** [comment]
Yes, it's a good (logical) reason.

But the name and id of the element _should_ not be long. But it not so for the classes, src, and href, and in particular for data-\* attributes.

**Comment by robinrendle** [comment]
I’m really surprised there wasn’t a rule in here about avoiding ids _because_ of their specificity. They’re simply too hazardous for the long-term maintenance of a project’s codebase.

**Comment by mdo** [comment]
ids can be helpful, but yes, they should be avoided in your CSS. I'll document that—and JS classes. Opening an new issue for that.

**Comment by GreenImp** [comment]
I know this issue is closed now, and I understand why you suggest to put class before ID, but why the suggested order for other attributes?

I always use this ordering:
`type, name, value, src, href, for, alt, title, data-*, id, class`
(I don't tend to use `aria-*` or `role`).

I feel that the first ones are the most important/relevant for defining the element, get less specific as you go along; therefore `class` is at the end as the least relevant.
I'm not suggesting one is write and the other is wrong, but would really like to hear why you chose the order that you did (genuine interest), as I can't see a particular order for the most part.
