### ISSUE TITLE
Missing meta tags

### ISSUE THREAD

**Issue by zlatanvasovic** [mdo/code-guide#82]
There aren't `<meta>` tags for author, description and keywords. You should add them for the robots. :smile:

**Comment by nhall** [comment]
Are there any robots that read/use `meta` tags with the keyword attribute? I know it was believed that Google used them for ranking but they have since [said they don't put any weight in them](http://googlewebmastercentral.blogspot.com/2009/09/google-does-not-use-keywords-meta-tag.html).

**Comment by alexdevero** [comment]
Meta tag with keyword attribute was used by bing and other search engines to recognize spam pages. This method is not used anymore, so tag with keyword attribute is useless.

**Comment by zlatanvasovic** [comment]
I don't want `keywords` for spam. Lol. :p 

They're there for the better search.

**Comment by alexdevero** [comment]
They're useless for better search, just take a look at html code of github.com...

**Comment by zlatanvasovic** [comment]
I don't think that we should compare GitHub site and some other small site
(like this one).

Let the @mdo decide. :p

2014-03-29 16:10 GMT+01:00 Alex Devero notifications@github.com:

> They're useless for better search, just take a look at html code of
> github.com...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mdo/code-guide/issues/82#issuecomment-38998242
> .

## 

Zlatan Vasović - _ZDroid_

**Comment by zatkin** [comment]
The `keywords` meta tag does not help your web ranking at all.

"About a decade ago, search engines judged pages only on the content of web pages, not any so-called "off-page" factors such as the links pointing to a web page. In those days, keyword meta tags quickly became an area where someone could stuff often-irrelevant keywords without typical visitors ever seeing those keywords. Because the keywords meta tag was so often abused, many years ago Google began disregarding the keywords meta tag."

http://googlewebmastercentral.blogspot.in/2009/09/google-does-not-use-keywords-meta-tag.html

**Comment by mdo** [comment]
Meh, if a PR is opened to add some of these, I'll consider it. Otherwise, not worth my time too much :).

**Comment by zlatanvasovic** [comment]
No probs.

2014-06-16 19:14 GMT+02:00 Mark Otto notifications@github.com:

> Meh, if a PR is opened to add some of these, I'll consider it. Otherwise,
> not worth my time too much :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mdo/code-guide/issues/82#issuecomment-46206672.

## 

Zlatan Vasović - _ZDroid_
